# Cloudflare Worker 项目的顶级配置文件
name = "community-board"
main = "worker/src/index.ts"
compatibility_date = "2024-05-30"
compatibility_flags = [ "nodejs_compat" ]

# [vars]
# This section defines environment variables for your Worker.
# The auth code uses these to configure Passkeys correctly.
[vars]
RP_NAME = "Community Board"
RP_SUBTITLE = "An opensource-friendly forum"
RP_ID = "serverless-bbs.anquanssl.com"
ORIGIN = "https://serverless-bbs.anquanssl.com"
R2_PUBLIC_URL = "https://pub-610f99178b7e4cfb9e2fea44c1488cae.r2.dev"
API_WORKER_URL = "https://serverless-bbs-api.anquanssl.com"
REGISTER_ENABLED = false

# [dev]
# This block configures the local development server (`wrangler dev`).
# Explicitly setting the port helps avoid ambiguity and potential conflicts.
[dev]
port = 8787

# 将前端 UI 构建的静态资源目录绑定到 Worker.
[[sites]]
bucket = "./ui/dist"

# D1 数据库绑定.
[[d1_databases]]
binding = "DB"
database_name = "community-db"
database_id = "3533d88d-593b-4137-ae4a-e19a28970dbd"
migrations_dir = "worker/migrations"

# KV Namespace 绑定.
[[kv_namespaces]]
binding = "KV_SESSIONS"
id = "5238ba5971a947afa77850d7c75bfc24"

# R2 Bucket 绑定.
[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "community-assets"

[env.dev]

[env.dev.vars]
RP_NAME = "开发版论坛"
RP_SUBTITLE = "本地测试环境"
RP_ID = "localhost"
ORIGIN = "//localhost:5173"
R2_PUBLIC_URL = "//localhost:8787/r2"
API_WORKER_URL = "//localhost:8787"
